modLoader="javafml"
loaderVersion="[30,)"
license="Apache"
[[mods]]
modId="vycs_addon"
version="1.1.6"
displayName="Valeyard Collections Addon"
displayURL="https://valeyardstudios.wixsite.com/valeyardstudios"
credits="TheVale"
authors="TheVale"
description='''Valeyard Collections Model Pack for Dalek Mod Update 65'''